### ISSUE TITLE
:test node variable visibility issue

### ISSUE THREAD

**Issue by mrrodriguez** [rbrush/clara-rules#101] opened 2015-03-06 03:00 UTC
I believe I have stumbled across another regression related to the work done with 
https://github.com/rbrush/clara-rules/issues/97 and https://github.com/rbrush/clara-rules/issues/96.

I'd expect the following to work, but they throw exceptions:
Note: I put a few newlines in the error messages so the lines weren't super long.

```clj
;; in clara.test-rules 

(mk-session [(dsl/parse-rule [[?res <- (acc/all) :from [Temperature (= ?t temperature)]]
                              [:test (or (< ?t 10)
                                         (< 10 ?t))]]

                             (println "hello world"))])
;; Results in

ExceptionInfo Using variable that is not previously bound. This can happen when a test expression 
uses a previously unbound variable, or if a variable is referenced in a nested part of a 
parent expression, such as (or (= ?my-expression my-field) ...). 
Unbound variables: #{?__gen__11923}  clojure.core/ex-info (core.clj:4403)

```
This one has an issue with the auto-generated symbol of the :test node.

Then for an accumulator, we get a slightly different result, but still broken:
```clj
(mk-session [(dsl/parse-rule [[?res <- (acc/all) :from [Temperature (= ?t temperature)]]
                              [:test (or (empty? ?res)
                                         (not-empty ?res))]]

                             (println "hello world"))])

;; Results in

ExceptionInfo Using variable that is not previously bound. This can happen when a test 
expression uses a previously unbound variable, or if a variable is referenced in a nested 
part of a parent expression, such as (or (= ?my-expression my-field) ...). 
Unbound variables: #{?res}  clojure.core/ex-info (core.clj:4403)
```

**Comment by rbrush** [comment] 2015-03-06 04:11
Ugh, my overzealous checks for an invalid condition didn't account for accumulators. I'm going to refactor this into a more robust approach so we can put these to bed. I'll get a fix posted in next couple days.

**Comment by rbrush** [comment] 2015-03-06 14:34
Pushed a fix in the above commit that handles this case. 

Note that I ran into some behavior that might not be what we want when running the examples Mike provided above. I logged issue #102 to track that.

**Comment by rbrush** [comment] 2015-03-06 14:36
The essence of the issue is that the rete transformation that pulls out arbitrary test functions from join nodes was also pulling out tests from test nodes...which is unnecessary and led to the creation of generated variables that didn't match. So I just added appropriate checks to not do this transformation on test nodes, did a bit of refactoring to eliminate some duplicate logic, and added tests to expose the issue.

**Comment by mrrodriguez** [comment] 2015-03-08 02:33
Thanks for the quick fix!

**Comment by rbrush** [comment] 2015-03-08 20:41
Merged into master. Closing in preparation for the 0.8.6 release.

**Closed by rbrush** 2015-03-08 20:41 UTC
