### ISSUE TITLE
Relaxing restriction on how accum :result-binding can be used

### ISSUE THREAD

**Issue by mrrodriguez** [rbrush/clara-rules#132] opened 2015-10-16 19:11 UTC
I see the change from
https://github.com/rbrush/clara-rules/commit/ca68b9dc140dcb088c5236eb22d2cb6be5d4b5ac
is meant to prevent `:result-binding`s from being used my subsequent conditions within a rule LHS.

I'm not positive on the reason behind this, so I'd certainly like your feedback on it.  However, I am thinking that the reason for this is that Clara will re-order the conditions in a rule so that the order of conditions is: simple conditions -> negation conditions -> accumulator conditions -> test conditions.  I see this in the clara.rules.compiler/condition-comp function.

This restriction is interestingly not always applicable to simple conditions if the binding is not a direct field equality unification.

I this is best just demonstrated with an example.
Note: This example is obviously contrived to just make it as short as I could easily demonstrate.  I realize it doesn't make a lot of sense to do it.

This works:
 ```clj
(let [r (dsl/parse-rule [[?t <- (acc/max :temperature :returns-fact true) :from [Temperature]]
                         [Temperature (= (identity ?t) this)]]

                        (println "?t" ?t))
      s (mk-session [r])]
  (-> s
      (insert (->Temperature 1 "MCI"))
      fire-rules))

?t #clara.rules.testfacts.Temperature{:temperature 1, :location MCI}
;= #<LocalSession clara.rules.engine.LocalSession@764670aa>
 
```

This does not work:
 ```clj
(let [r (dsl/parse-rule [[?t <- (acc/max :temperature :returns-fact true) :from [Temperature]]
                         [Temperature (= ?t this)]]

                        (println "?t" ?t))
      s (mk-session [r])]
  (-> s
      (insert (->Temperature 1 "MCI"))
      fire-rules))

ExceptionInfo Using accumulator result bindings in other expressions in a rule left-hand side is currently not supported. Binding: :?t in production {:lhs [{:result-binding :?t, :accumulator (clara.rules.accumulators/max :temperature :returns-fact true), :from {:type clara.rules.testfacts.Temperature, :constraints []}} {:type clara.rules.testfacts.Temperature, :constraints [(= ?t this)]}], :rhs (println "?t" ?t)}  clojure.core/ex-info (core.clj:4403)
 
```

The reason (I believe) is that the difference in the condition constraint `(= ?t this)` vs `(= (identity ?t) this)`.
When an seq-style expression is involved in the binding unification, the operation is "deferred" into a later :test condition.  With this, I believe some of the efficiency of the hash-based join may be lost, but I am not positive there.

--

In the case of negation conditions, I cannot find a way where I can successfully use a `:result-binding` from an accumulator at all.  However, the error message is for negation conditions hitting thi srestriction are more mysterious than the errors for simple conditions.

```clj
(let [r (dsl/parse-rule [[?t <- (acc/max :temperature :returns-fact true) :from [Temperature]]
                         [:not [Temperature (= (identity ?t) this)]]]

                        (println "?t" ?t))
      s (mk-session [r])]
  (-> s
      (insert (->Temperature 1 "MCI"))
      fire-rules))

ExceptionInfo Using variable that is not previously bound. This can happen when an expression uses a previously unbound variable, or if a variable is referenced in a nested part of a parent expression, such as (or (= ?my-expression my-field) ...). 
Unbound variables: #{?t}  clojure.core/ex-info (core.clj:4403)

;;; As well as

(let [r (dsl/parse-rule [[?t <- (acc/max :temperature :returns-fact true) :from [Temperature]]
                         [:not [Temperature (= ?t this)]]]

                        (println "?t" ?t))
      s (mk-session [r])]
  (-> s
      (insert (->Temperature 1 "MCI"))
      fire-rules))

ExceptionInfo Using accumulator result bindings in other expressions in a rule left-hand side is currently not supported. Binding: :?t in production {:lhs [{:result-binding :?t, :accumulator (clara.rules.accumulators/max :temperature :returns-fact true), :from {:type clara.rules.testfacts.Temperature, :constraints []}} [:not {:type clara.rules.testfacts.Temperature, :constraints [(= ?t this)]}]], :rhs (println "?t" ?t)}  clojure.core/ex-info (core.clj:4403)

```

I haven't went into the details yet of why negation conditions are not behaving the same as the simple conditions here.

---

I think this behavior is somewhat confusing and the limitation has caused me some difficulty in rules that we do typically want to write.  I realize it can be worked around by separating the accumulated `:result-binding` rule from the rest of the logic that needs to reason about it.  This can be done via an intermediate fact to relay the accumulated result information to further conditions in another rule.

I'm curious if this restriction could be reconsidered and removed by moving the unification to a :test condition when a simple condition or negation condition wished to refer to the `:result-binding` of an accumulator.  I think this may be straight forward for simple conditions.  I'm not sure on negation conditions as I've mentioned above.

Thanks for the feedback on this!

**Comment by rbrush** [comment] 2015-10-16 20:44
This is a bug, in both the negation and the non-negation flow. I had disallowed using accumulator results in bindings because I didn't know of a need, and I didn't see a good way to support it when dealing with edge cases around the extraction of tests from conditions. But this is something we should support.

Looking at it now, I think we I see an approach that is simple and workable but I need to dig a bit deeper first. I'll do so and report back here.

**Comment by rbrush** [comment] 2015-10-18 14:38
These should be addressed in the above commits. The first removes the constraint on using accumulator results in other conditions, and the second fixes a bug in the negation logic that prevents it from seeing the result bindings of accumulators.

Merging in these fixes makes sense to me as they address the issue without any known regression, but it might also be worthwhile to clean up the logic around this in general. I logged issue #133 to track that.

Let me know if these don't fix the problem you ran into, or if you have any other suggestions in this space.

**Comment by mrrodriguez** [comment] 2015-10-21 14:12
Hi.  Sorry for the delayed feedback.  I'm looking through these changes and testing them against the issues I was seeing originally.  I'll get back with feedback sometime today.  I appreciate the quick feedback and work on this.

**Comment by mrrodriguez** [comment] 2015-10-21 19:15
Ok, I looked over this today and tested against my concrete situation I had where it came up recently.  It looks to me that everything is working as I'd expect in that situation with these changes in place.
I also do not see any regressions currently against the projects I have using Clara.

I do have a question on the changes @ 
https://github.com/rbrush/clara-rules/commit/1fde77b12bc952eaf5f8a6304ffa34bd1f305419#diff-00da05e66726186c05209662d990b97cR604
Initially this change worried me because I thought it meant if an accumulator changed what it returned it wouldn't propagate.  However, there would always be a retraction prior to that from what I can tell.
The more I played around with this, the more I thought it seemed to be alright.  My question on this really is what sort of situation is it meant to catch?  Perhaps just for my own understanding of the changes.
Thanks!

**Comment by rbrush** [comment] 2015-10-21 21:54
The "previous-result" variable could probably use a better name. That check isn't to compare it with the previous result of the accumulator, but with any other constraint that uses the same binding. For instance, a rule like this:

```clj
(defrule example
   [?temp <- Temperature (= ?t temperature)]
   [?t <- (acc/max :temperature) :from [Temperature]]
  =>
  (println ?temp "is the maximum temperature fact!"))
```

(This is contrived and a bad way to write this logic, of course.) 

Notice that ?t is bound in the first condition, and re-bound as the result of the accumulator. So we'd only want the rule to fire if the ?t bound above matches the ?t resulting from the accumulator...which is what that check does. This wasn't necessary when we disallowed the use of accumulator results in other expressions, but now that we support it we have to make sure they are consistent.

It's also worth noting that we can put this logic in the accumulator node because we sort accumulators to be after other nodes in the network.

**Comment by rbrush** [comment] 2015-10-22 11:17
I went ahead and clarified the code comment on this topic a bit. Since this is working across multiple projects without regression and solves the problem, I went ahead and merged this into master as well.

We're tracking future improvements in issue #133, so I don't think there is anything left to do on this issue and will close it. We can reopen or create a new issue if you disagree.

**Closed by rbrush** 2015-10-22 11:17 UTC

**Comment by mrrodriguez** [comment] 2015-10-22 13:21
Thanks for that explanation!  That makes sense to me now.  I also think the clarification to the commit you committed definitely helps as well.
