### ISSUE TITLE
IllegalArgumentException during "lein run" while working fine in "lein repl"

### ISSUE THREAD

**Issue by olivermg** [rbrush/clara-rules#212] opened 2016-08-12 13:42 UTC
I'm using clara-rules 0.11.1.

First the code:

```clojure
(ns claratest.core
  (:gen-class)
  (:require [clara.rules :refer :all]))

(defrecord Fact [])

(defquery get-facts []
  [?facts <- Fact])

(defn- run []
  (-> (mk-session)
      (fire-rules)
      (query get-facts)))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello, World!")
  (run)
  (println "Bye, World!"))
```

Running it in the REPL works fine:

```
claratest.core> (run)
()
```

but via `lein run` it throws an IllegalArgumentException, saying that "The query [...] is invalid or not included in the rule base." :

```
% lein run
Hello, World!
Exception in thread "main" java.lang.IllegalArgumentException: The query {:lhs [{:type claratest.core.Fact, :constraints [], :fact-binding :?facts}], :params #{}, :name "claratest.core/get-facts"} is invalid or not included in the rule base., compiling:(/private/var/folders/th/f2ks7qjn0g52279rdfnmjcsr0000gn/T/form-init5370267113791774844.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: The query {:lhs [{:type claratest.core.Fact, :constraints [], :fact-binding :?facts}], :params #{}, :name "claratest.core/get-facts"} is invalid or not included in the rule base.
	at clara.rules.platform$throw_error.invokeStatic(platform.cljc:5)
	at clara.rules.platform$throw_error.invoke(platform.cljc:5)
	at clara.rules.engine.LocalSession.query(engine.cljc:1174)
	at clara.rules$query.invokeStatic(rules.cljc:48)
	at clara.rules$query.doInvoke(rules.cljc:38)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at claratest.core$run.invokeStatic(core.clj:13)
	at claratest.core$run.invoke(core.clj:10)
	at claratest.core$_main.invokeStatic(core.clj:19)
	at claratest.core$_main.doInvoke(core.clj:15)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init5370267113791774844.clj:1)
	at user$eval5.invoke(form-init5370267113791774844.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
```

After scratching my head a bit I found out that you can avoid this Exception by replacing `(mk-session)` with `(mk-session 'claratest.core)`, thus stating the "rule namespace(s)" explicitly.

Not sure it's a bug as it might be the result of some AOT compilation stuff. However, I think most people would expect it to at least behave consistently during both `lein repl` & `lein run` (either both working or both failing).

**Comment by rbrush** [comment] 2016-08-12 14:53
Hey Oliver, 

I agree this is surprising. I think the problem is that ```lein run``` doesn't set the current namespace to the that of the main program. Clara looks at Clojure's \*ns\* var to determine what rules to load if none are provided, and if you add this line to your -main function, I think you'll see the "user" namespace.

```cli
(println "In namespace: " (ns-name *ns*))
```

So Clara scans that namespace for rules, and of course they aren't there. I'm guessing when using the REPL you're running in your claratest.core namespace, so *ns* is set to the expected value. 

An alternative would be either to explicitly state the namespace (as you found), or to statically define your ruleset, like so:

```cli
(def empty-session (mk-session))

(defn- run []
  (-> empty-session
      (fire-rules)
      (query get-facts)))
```

This works because (mk-session) is run when the claratest.core namespace is being loaded, so *ns* is pointing at it.

Thanks for bringing this up. I'm not sure there is a lot we can do in Clara for this case, but if nothing else we should be able to document this better. (When playing with this, I also noticed that the defsession macro isn't working quite like you might expect here, which is something we can fix.)

**Comment by olivermg** [comment] 2016-08-12 16:14
Hey Ryan,

first of all thanks for your quick answer.

Your assumption about this `*ns*` stuff seems to be correct. The namespace during `lein run` is indeed `user`.

Also, when switching to the `user` namespace in the REPL and then calling `(claratest.core/run)` (after making it public) raises the same exception.

I suppose this means that I was just lucky to not encounter this error in the REPL. I simply wasn't aware of that `mk-session` has to get hold of the specific namespace, which seems obvious when thinking about it.

Thus, making this behavior more explicit in the docs would for sure be of great help to new users and the workarounds provided seem sufficient (for me at least).

Thanks again. If I can be of any help then just let me know.

**Comment by rbrush** [comment] 2016-08-22 14:08
Alright, I clarified the *ns* behavior in the mk-session Clojure doc in the above commit. I don't think there's anything more to do here so I'm going to go ahead and close this, but we can reopen if you disagree, or create new issues  for further work.

**Closed by rbrush** 2016-08-22 14:08 UTC
